### ISSUE TITLE
PDF entry for networking close() slide leads to generic close() slide

### ISSUE THREAD

**Issue by Dook97** [devnull-cz/unix-linux-prog-in-c#53]
In the pdf index under section `network programming` subtopic `close` refers to a much earlier place in the document, which talks about general UNIX APIs and not about the relation of `close` to socket file descriptors etc. which was the intent.

**Comment by vladak** [comment]
Thanks for the report. Which version of the PDF (assuming the slides with comments) are you using ?

**Comment by Dook97** [comment]
The latest release - v99.

**Comment by vladak** [comment]
I don't seem to be able to replicate the issue, or maybe I misunderstood the description. Any chance you can show it to me after the lecture ?

**Comment by Dook97** [comment]
The issue is with the metadata. For example: if you open the pdf in firefox then open the "sections" panel and under the "network programming" section select "close" the document viewer will jump to page 64 instead of 168, which would be the correct destination.

Happens also with [zathura](https://git.pwmt.org/pwmt/zathura), so not a firefox bug I think.

If you still can't reproduce the issue with this description, I'll be happy to demonstrate after the lecture.
